In [2]:
import torch

tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [3]:
# float64 tensor
float_tensor = torch.tensor([1.5, 2.7, 3.3], dtype=torch.float64)
float_tensor

tensor([1.5000, 2.7000, 3.3000], dtype=torch.float64)

In [4]:
float_tensor.dtype

torch.float64

In [5]:
# most important params

float_tensor = torch.tensor([1.5, 2.7, 3.3],
                            dtype=torch.float32,
                            device="cpu",
                            requires_grad=False)
float_tensor

tensor([1.5000, 2.7000, 3.3000])

- dtype - what datatype is the tensor
- device - what device is your tensor on (cpu/cuda)
- requires_grad = wheter or not to track gradients with this tensor operations

In [6]:
fl32 = torch.tensor([3., 6., 9])
fl16 = fl32.type(torch.float16)
fl16

tensor([3., 6., 9.], dtype=torch.float16)

In [7]:
fl32 * fl16

tensor([ 9., 36., 81.])

In [8]:
fl32.shape

torch.Size([3])

In [9]:
fl32.size()

torch.Size([3])

In [10]:
print("Datatype:", fl32.dtype)
print("Shape:", fl32.shape)
print("Device:", fl32.device)

Datatype: torch.float32
Shape: torch.Size([3])
Device: cpu
